[environment]
mode = "dev"

[relayer_blockchain]
    # Allfet local node
    [relayer_blockchain.ChainId440]
    rpc_url = "http://127.0.0.1:9944/"
    project_id = "{{ PROJECT_ID_440 }}"
    pk = "{{ PK_440 }}"
    wait_block_validation = 1
    block_validation_second_per_block = 1
    smart_contract_address = "0xa92D0afeB8077893b16769B1BBf011509731bA49"
    genesis_block = 0
    client = ""

    # GETH node
    [relayer_blockchain.ChainId1337]
    rpc_url = "http://127.0.0.1:8545/"
    project_id = "{{ PROJECT_ID_1337 }}"
    pk = "{{ PK_1337 }}"
    wait_block_validation = 1
    block_validation_second_per_block = 5
    smart_contract_address = "0x712516e61C8B383dF4A63CFe83d7701Bce54B03e"
    genesis_block = 0
    client = "middleware"

    [relayer_blockchain.ChainId80002]
    rpc_url = "https://polygon-amoy.g.alchemy.com/v2/"
    project_id = "{{ PROJECT_ID_80002 }}"
    pk = "{{ PK_80002 }}"
    wait_block_validation = 6
    block_validation_second_per_block = 12
    smart_contract_address = "0x6dC7CfE7Ce3c4d071fABC7B616E94fBba361B212"
    genesis_block = 8267279
    client = "middleware"

[relayer_register]
# RabbitMQ Broker
host = "{{ RELAYER_REGISTER_HOST }}"
port = "{{ RELAYER_REGISTER_PORT }}"
user = "{{ RELAYER_REGISTER_USER }}"
password = "{{ RELAYER_REGISTER_PASSWORD }}"
queue_name = "{{ RELAYER_REGISTER_QUEUE_NAME }}"

[relayer_event_rules]
    [relayer_event_rules.OperationCreated]
    origin = "chainIdFrom"
    has_block_finality = true
    chain_func_name = 'chainIdTo'
    func_name = "sendFeesLockConfirmation"
    depends_on = 'FeesDeposited'

    [relayer_event_rules.FeesDeposited]
    origin = "chainIdTo"
    has_block_finality = true
    chain_func_name = 'chainIdTo'
    func_name = "sendFeesLockConfirmation"
    depends_on = 'OperationCreated'

    [relayer_event_rules.FeesDepositConfirmed]
    origin = "chainIdTo"
    has_block_finality = false
    chain_func_name = 'chainIdFrom'
    func_name = "receiveFeesLockConfirmation"

    [relayer_event_rules.FeesLockedConfirmed]
    origin = "chainIdFrom"
    has_block_finality = false
    chain_func_name = 'chainIdFrom'
    func_name = "confirmFeesLockedAndDepositConfirmed"

    [relayer_event_rules.FeesLockedAndDepositConfirmed]
    origin = "chainIdFrom"
    has_block_finality = false
    chain_func_name = 'chainIdTo'
    func_name = "completeOperation"

    [relayer_event_rules.OperationFinalized]
    origin = "chainIdTo"
    has_block_finality = false
    chain_func_name = 'chainIdFrom'
    func_name = "receivedFinalizedOperation"
