[environment]
mode = "prod"

[relayer_blockchain]
    # Polygon testnet
    [relayer_blockchain.ChainId80002]
    rpc_url = "https://polygon-amoy.g.alchemy.com/v2/"
    project_id = "{{ PROJECT_ID_80002 }}"
    pk = "{{ PK_80002 }}"
    wait_block_validation = 6
    smart_contract_address = "0x6dC7CfE7Ce3c4d071fABC7B616E94fBba361B212"
    genesis_block = 8267279
    client = "middleware"

    # Allfest tesnet 
    [relayer_blockchain.ChainId441]
    rpc_url = "https://harmonie-endpoint-02.allfeat.io/"
    project_id = "{{ PROJECT_ID_441 }}"
    pk = "{{ PK_441 }}"
    wait_block_validation = 2
    smart_contract_address = "0xE86603d2b796412432237c4C0837F68175f13D08"
    genesis_block = 1091325
    client = ""

    # Sepolia
    [relayer_blockchain.ChainId11155111]
    rpc_url = "https://eth-sepolia.g.alchemy.com/v2/"
    project_id = "{{ PROJECT_ID_11155111 }}"
    pk = "{{ PK_11155111 }}"
    wait_block_validation = 2
    smart_contract_address = "0xfC7D37432d637e334b391F5ecf283d69783dBe64"
    genesis_block = 6186178
    client = "middleware"

  # Ethereum mainnet
  [relayer_blockchain.ChainId1]
    rpc_url = "https://eth-mainnet.g.alchemy.com/v2/"
    project_id = "{{ PROJECT_ID_1 }}"
    pk = "{{ PK_1 }}"
    wait_block_validation = 2
    smart_contract_address = "0xE86603d2b796412432237c4C0837F68175f13D08"
    genesis_block = 1091325
    client = ""

[relayer_register]
# RabbitMQ Broker
host = "{{ RELAYER_REGISTER_HOST }}"
port = "{{ RELAYER_REGISTER_PORT }}"
user = "{{ RELAYER_REGISTER_USER }}"
password = "{{ RELAYER_REGISTER_PASSWORD }}"
queue_name = "{{ RELAYER_REGISTER_QUEUE_NAME }}"

[relayer_event_rules]
    [relayer_event_rules.OperationCreated]
    origin = "chainIdFrom"
    has_block_finality = true
    chain_func_name = 'chainIdTo'
    func_name = "sendFeesLockConfirmation"
    depends_on = 'FeesDeposited'

    [relayer_event_rules.FeesDeposited]
    origin = "chainIdTo"
    has_block_finality = true
    chain_func_name = 'chainIdTo'
    func_name = "sendFeesLockConfirmation"
    depends_on = 'OperationCreated'

    [relayer_event_rules.FeesDepositConfirmed]
    origin = "chainIdTo"
    has_block_finality = false
    chain_func_name = 'chainIdFrom'
    func_name = "receiveFeesLockConfirmation"

    [relayer_event_rules.FeesLockedConfirmed]
    origin = "chainIdFrom"
    has_block_finality = false
    chain_func_name = 'chainIdFrom'
    func_name = "confirmFeesLockedAndDepositConfirmed"

    [relayer_event_rules.FeesLockedAndDepositConfirmed]
    origin = "chainIdFrom"
    has_block_finality = false
    chain_func_name = 'chainIdTo'
    func_name = "completeOperation"

    [relayer_event_rules.OperationFinalized]
    origin = "chainIdTo"
    has_block_finality = false
    chain_func_name = 'chainIdFrom'
    func_name = "receivedFinalizedOperation"
