[environment]
mode = "dev"

[relayer_blockchain]
    # Allfet local node
    [relayer_blockchain.ChainId440]
    rpc_url = "http://127.0.0.1:9944/"
    project_id = "{{ PROJECT_ID_440 }}"
    pk = "{{ PK_440 }}"
    wait_block_validation = 6
    smart_contract_address = "0xa92D0afeB8077893b16769B1BBf011509731bA49"
    genesis_block = 0
    client = ""

    # GETH node
    [relayer_blockchain.ChainId1337]
    rpc_url = "http://127.0.0.1:8545/"
    project_id = "{{ PROJECT_ID_1337 }}"
    pk = "{{ PK_1337 }}"
    wait_block_validation = 6
    smart_contract_address = "0x8613A4029EaA95dA61AE65380aC2e7366451bF2b"
    genesis_block = 0
    client = "middleware"

    # Anvil local node
    [relayer_blockchain.ChainId31337]
    rpc_url = "http://127.0.0.1:8545/"
    project_id = "{{ PROJECT_ID_31337 }}"
    pk = "{{ PK_31337 }}"
    wait_block_validation = 1
    smart_contract_address = "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
    genesis_block = 0
    client = "middleware"

    [relayer_blockchain.ChainId80002]
    rpc_url = "https://polygon-amoy.g.alchemy.com/v2/"
    project_id = "{{ PROJECT_ID_80002 }}"
    pk = "{{ PK_80002 }}"
    wait_block_validation = 6
    smart_contract_address = "0x6dC7CfE7Ce3c4d071fABC7B616E94fBba361B212"
    genesis_block = 8267279
    client = "middleware"

    [relayer_blockchain.ChainId441]
    rpc_url = "https://harmonie-endpoint-02.allfeat.io/"
    project_id = "{{ PROJECT_ID_441 }}"
    pk = "{{ PK_441 }}"
    wait_block_validation = 6
    smart_contract_address = "0x55e05213724f97c5C1ee976B5a219a7eB54EE1F1"
    genesis_block = 1015519
    client = ""

    [relayer_blockchain.ChainId123]
    rpc_url = "https://fake.rpc_url.org"
    project_id = "{{ PROJECT_ID_123 }}"
    pk = "{{ PK_123 }}"
    wait_block_validation = 6
    smart_contract_address = "0x1234567890abcdef1234567890abcdef12345678"
    genesis_block = 123456789
    client = "middleware"


    [relayer_blockchain.ChainId456]
    rpc_url = "https://fake.rpc_url.org"
    project_id = "{{ PROJECT_ID_456 }}"
    pk = "{{ PK_456 }}"
    wait_block_validation = 1
    smart_contract_address = "0x1234567890abcdef1234567890abcdef12345678"
    genesis_block = 123456789
    client = "middleware"

    [relayer_blockchain.ChainId789]
    rpc_url = "https://fake.rpc_url.org"
    project_id = "{{ PROJECT_ID_789 }}"
    pk = "{{ PK_789 }}"
    wait_block_validation = 1
    smart_contract_address = "0x1234567890abcdef1234567890abcdef12345678"
    genesis_block = 123456789
    client = "middleware"

[relayer_register]
# RabbitMQ Broker
host = "{{ RELAYER_REGISTER_HOST }}"
port = "{{ RELAYER_REGISTER_PORT }}"
user = "{{ RELAYER_REGISTER_USER }}"
password = "{{ RELAYER_REGISTER_PASSWORD }}"
queue_name = "{{ RELAYER_REGISTER_QUEUE_NAME }}"